POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "wallet_status",
    "params": {}
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_utxo",
    "params": {}
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_utxo",
    "params": {
        "sort": {
            "field": "amount",
            "direction": "asc"
        }
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_utxo",
    "params":  {
        "count": 10,
        "skip": 0,
        "sort": {
            "field": "status"
        }
    }
   
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "set_confirmations_count",
    "params": {
        "count": 5
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_confirmations_count",
    "params": {}
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_offers_list",
    "params": {}
}
###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_offers_list",
    "params": {}
}

###
POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 126,
    "method": "swap_get_balance",
    "params": {
        "coin": "btc"
    }
}
###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_offers_board",
    "params": {}
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_create_offer",
    "params": {
        "send_amount": 44000000000,
        "send_currency": "beam",
        "receive_amount": 2000000000,
        "receive_currency": "btc",
        "beam_fee": 100,
        "fee_rate": 90000,
        "offer_expires": 30,
        "comment": "API"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 126,
    "method": "swap_offer_status",
    "params": {
        "tx_id": "a36671ceb9d844e2baa44798ee1e915a"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 126,
    "method": "swap_cancel_offer",
    "params": {
        "txId" : "a36671ceb9d844e2baa44798ee1e915a"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 126,
    "method": "swap_publish_offer",
    "params": {
        "token": "TJfqqvZNnsGH33yWH8YYvma8eoUWKnecn6mfC97MrrdMw1a8q6hVTpTCrGqcmkzDCyxc6hrzARRUakreNGopRXUxfYAPGS1RS3sYdr3wrXtoycDNTsPWcDTzqUt68sMqCtRtEt2XGZR7x8QXqDXNiexecpdK467Wo8zehxNA"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_accept_offer",
    "params": {
        "receive_amount": 500000000,
        "receive_currency": "btc",
        "send_amount": 5500000000,
        "send_currency": "beam",
        "beam_fee": 100,
        "fee_rate": 90000,
        "comment": "API-accept",
        "token" : "6xewkUBnRZXrRKwwnseyFaufaPvGAvcjMG1DmQKtJvyyKvamsmRgcAVoyBFcDWp93ZcF6sFuiGYUmoLFkrXQLnASyX53ppziXy1MNePox7TGRZX1smSBuNMBgQCoQzW2j3EEs3yqRXgF6wkpjMZq6iCrY1E9sxDoGGxwyEt"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 126,
    "method": "swap_accept_offer",
    "params": {
        "token": "Jk6G34NFBZVdUhZkRAy5eetuuZ1vivQcP7PiwcKC7G4WVvY4P5X2qABegCAtCAP8WTLffaWysu8VUQCotc6UPxLLELPTJzEbZpeG9Z19UU5cHRe47p6KTgF7sE3b1EiqWMpPuR1rjtDgAKfjouksQgPg9d3DmTnDQMiD"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_list",
    "params": {}
}


######## Explorer node #######################
###

GET http://127.0.0.1:8888/status HTTP/1.1

###

GET http://127.0.0.1:8888/blocks?height=13600&n=100 HTTP/1.1

###

GET http://127.0.0.1:8888/swap_offers HTTP/1.1

###
