POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "wallet_status",
    "params": {}
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_offers_list",
    "params": {}
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_create_offer",
    "params": {
        "send_amount": 1000000,
        "send_currency": "beam",
        "receive_amount": 2000000,
        "receive_currency": "btc",
        "beam_fee": 100,
        "btc_fee_rate": 90000,
        "offer_expires": 30,
        "comment": "API"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "swap_offer_status",
    "params": {
        "token": "6xf5BNCnTjvmnXKtK79hDKEKMFUwpNLTPpM6PYtFrMs4SX7TktazTgAZ9EmMnLyvU2UEaVyDrtWdKkQgyu9ADSV9nPdrLq3NSYbXjYgtpuA6UADVW6REVmDVpcigkLnFtcQnsNCcjKpH5Ayy2dQoDshXoz1p5iHn686cB8e"
    }
}

###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_list",
    "params": {}
}

###
