POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_issue",
    "params": {
         "value": 6,
         "assetid": 1
    }
}
###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_consume",
    "params": {
         "value": 4,
         "assetid": 1
    }
}
###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_info",
    "params": {
         "assetid": 1
    }
}
###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_asset_info",
    "params": {
         "assetid": 1
    }
}
###

POST http://127.0.0.1:10000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_info",
    "params": {
         "assetid": 1
    }
}
###