POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_issue",
    "params": {
         "value": 6,
         "asset_id": 2
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_consume",
    "params": {
         "value": 4,
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_info",
    "params": {
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_asset_info",
    "params": {
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_info",
    "params": {
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_list",
    "params": {
       "assets": true
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
	"jsonrpc":"2.0",
	"id": 4,
	"method":"tx_status",
	"params":
	{
		"txId" : "837a68432ed34dbe98f758614188a7db"
	}
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_utxo"
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_utxo",
    "params": {
         "assets": true,
         "filter" : {
             "asset_id": 1
         }
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_split",
    "params": {
         "coins" : [2, 2],
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "wallet_status",
    "params": {
         "assets" : true
    }
}

###
