POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_issue",
    "params": {
         "value": 6,
         "asset_id": 2
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_consume",
    "params": {
         "value": 4,
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_info",
    "params": {
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "get_asset_info",
    "params": {
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_asset_info",
    "params": {
         "asset_id": 1
    }
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
    "jsonrpc": "2.0",
    "id": 1236,
    "method": "tx_list",
    "params": {}
}

###
POST http://127.0.0.1:15000/api/wallet HTTP/1.1
content-type: application/json-rpc

{
	"jsonrpc":"2.0",
	"id": 4,
	"method":"tx_status",
	"params":
	{
		"txId" : "95ac4d97843340f88bfa8b50f0991623"
	}
}

###
