import Beam.Wallet 1.0

ConfirmationDialog {
    TokenBootstrapManager {
        id: instance
    }
    property alias model: instance
    property var checkTokenForDuplicate: function(token) {
        model.checkTokenForDuplicate(token);
    }
    property bool isOwn: false
    width: 460
    title: isOwn
        //% "You cannot accept your own offer"
        ? qsTrId("accept-own-offer-allert-head")
        //% "Оffer is already accepted"
        : qsTrId("swap-offer-duplicate-title")
    
    text: isOwn
        //% "The swap token was generated by you, and therefore cannot be accepted."
        ? qsTrId("accept-own-offer-allert-body")
/*% "The offer with this transaction token is already accepted.
Please check the swap token and try again."
*/
        : qsTrId("swap-offer-duplicate-message")
    
    okButtonText: isOwn
        //% "I understand"
        ? qsTrId("swap-alert-confirm-button")
        //% "ok"
        : qsTrId("swap-offer-duplicate-confirm-button")
    okButtonIconSource:     "qrc:/assets/icon-done.svg"
    cancelButtonVisible:    false
}
