call make_shader dummy/contract
call make_shader faucet/contract
call make_shader mirrorcoin/contract
call make_shader oracle/contract
call make_shader perpetual/contract
call make_shader pipe/contract
call make_shader playground/contract
call make_shader roulette/contract
call make_shader sidechain/contract
call make_shader StableCoin/contract
call make_shader upgradable/contract
call make_shader vault/contract
call make_shader voting/contract
call make_shader demoXdao/contract

call make_shader faucet/app
call make_shader mirrorcoin/app
call make_shader perpetual/app
call make_shader playground/app
call make_shader roulette/app
call make_shader vault/app
call make_shader voting/app
call make_shader demoXdao/app
